name: 🐩 Snyk Test & Monitor

on:
  schedule:
    # At 06:00 on Monday
    - cron: "0 6 * * MON"
  workflow_dispatch:

jobs:
  test-and-monitor:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Authenticate
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Update snapshot at Snyk.io
        continue-on-error: true
        run: snyk monitor

      - name: Test dependencies for known issues
        run: snyk test
